name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - run: npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Typecheck API
        run: npm exec nx typecheck api

      - name: Build API
        run: npm exec nx build api

      - name: Build web
        env:
          NEXT_PUBLIC_APP_URL: https://trchat.co
          NEXT_PUBLIC_API_URL: https://api.trchat.co/api
        run: npm exec nx build web
